# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'sdl-rkx_Example' do
  pod 'sdlrkx', :path => '../'
  pod 'ResearchKit', '~> 1.4'
end

target 'sdl-rkx_Tests' do
  pod 'sdlrkx', :path => '../'
  pod 'ResearchKit', '~> 1.4'
end
