# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'sdl-rkx_Example' do
  pod 'sdl-rkx', :path => '../'
  pod 'ResearchKit', :git => 'https://github.com/ResearchKit/ResearchKit.git'
end

target 'sdl-rkx_Tests' do
  pod 'sdl-rkx', :path => '../'
  pod 'ResearchKit', :git => 'https://github.com/ResearchKit/ResearchKit.git'
end
